name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
        go get -v -u github.com/gorilla/mux
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com

      - name: Build and Push to GitHub Packages
        run: |
          docker build --pull --rm -f "Dockerfile" -t docker.pkg.github.com/databess/go-api:latest "."
          docker push docker.pkg.github.com/databess/go-api:latest
