name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
    - name: List
      run: ls -l /usr/local/go/src/github.com | grep gorilla
    - name: Workspace
      run: cd $GOPATH
    - name: Get
      run: go get -v -u github.com/gorilla/mux
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
